### PR TITLE
Ornl aisd ex

### PR DESCRIPTION
**Pull request by kshitij-v-mehta**
This PR is currently for review only as we need to decide the destination repo and branch (currently set to allaffa/main).

This PR adds the capability of reading in tar.gz files for preprocessing in addition to the existing mollist.txt. Now, we can read in both GDB-9-Ex as well as ORNL_AISD_Ex datasets. 

New parser arguments `--input_data` and `--tmpfs` have been added that will accept a path to the input data (directory of tar files or mollist.txt) and tmpfs for extracting tar files. Tar files are extracted into tmpfs and the resulting molecule directories are then parsed to generate graph objects.

### CODE REVIEW

**Comment by kshitij-v-mehta** [comment]
Also adding @jychoi-hpc to review PR.

**Comment by kshitij-v-mehta** [comment]
Max, as this branch was cloned from the ddstore_equivariant branch from your fork, there are several commits from that branch that are visible in this PR. Please ignore those for now as we decide on where this PR should be merged.

**Comment by jychoi-hpc** [comment]
I made some minor changes and it works. 

Here are my changes:
```
         # Iterate through molecule directories or tar files and create graph objects
         for item in iterate_tqdm(dirlist, verbosity_level=2, desc="Load"):
+            if item == "README.txt":
+                continue
             fullpath = os.path.join(dirpath, item)
 
             # Verify that files in the directory are either tar.gz files or molecule directories
             if (not fullpath.endswith(".tar.gz")) and (not os.path.isdir(fullpath)):
-                raise ("Can't understand if {} is a molecule directory or tar.gz file".format(fullpath))
+                raise RuntimeError("Can't understand if {} is a molecule directory or tar.gz file".format(fullpath))
 
             # If tar.gz files, extract tar file in a tmp dir
             if fullpath.endswith(".tar.gz"):
                 extract_path = extract_tar_file(fullpath, tmpfs)
                 mdirs = [os.path.abspath(d) for d in os.scandir(extract_path) if d.is_dir()]
                 for mdir in mdirs:
-                    data_object = dftb_to_graph(mdir, dftb_node_types, var_config)
-                    self.dataset.append(data_object)
+                    try:
+                        data_object = dftb_to_graph(mdir, dftb_node_types, var_config)
+                        self.dataset.append(data_object)
+                    except:
+                        pass
```

Just for your information, I put a `try-except` block to handle the following error:
```
Traceback (most recent call last):
  File "/gpfs/alpine/lrn026/world-shared/jyc/HydraGNN-max/examples/dftb_uv_spectrum/train_discrete_uv_spectrum.py", line 241, in <module>
    total = DFTBDataset(
  File "/gpfs/alpine/lrn026/world-shared/jyc/HydraGNN-max/examples/dftb_uv_spectrum/train_discrete_uv_spectrum.py", line 132, in __init__
    data_object = dftb_to_graph(mdir, dftb_node_types, var_config)
  File "/gpfs/alpine/lrn026/world-shared/jyc/HydraGNN-max/examples/dftb_uv_spectrum/train_discrete_uv_spectrum.py", line 69, in dftb_to_graph
    ytarget = np.loadtxt(
  File "/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: /tmp/jyc/ornl_aisd_ex_unprocessed/mol_9054620/EXC.DAT not found.
```

**Comment by kshitij-v-mehta** [comment]
Closing this PR to create a new one

**Pull request closed without merging**
