### PR TITLE
Update vasp german

### PR DESCRIPTION
**Pull request by jychoi-hpc**
Testing `train.py` running on Andes. 

Getting some strange system error (bus error) with `train_binaries_predict_ternaries.py`. I am still checking.

### CODE REVIEW

**Comment by allaffa** [comment]
Based on the GitHub issue that you mentioned din your last email
[https://gitlab.com/ase/ase/-/merge_requests/3253](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgitlab.com%2Fase%2Fase%2F-%2Fmerge_requests%2F3253&data=05%7C02%7Clupopasinim%40ornl.gov%7Cb298f209a6884625d40708dc31a59e7e%7Cdb3dbd434c4b45449f8a0553f9f5f25e%7C1%7C0%7C638439834593263234%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=SPLcWCi%2BNV8BbL9HBRxhlV5uuPk9Y%2BOyHsAu%2BY53%2FBo%3D&reserved=0)

and based on this documentation
https://wiki.fysik.dtu.dk/ase/ase/io/io.html

we should safeguard ASE from using multi-threading by setting `parallel=False`. However, your PR does not do this anywhere. 
How did you fix the errors that I was getting?

**Comment by jychoi-hpc** [comment]
It is fixed from the ASE library itself (conda environment).

**Comment by jychoi-hpc** [comment]
`parallel=False` is put in the ASE library:
```
/lustre/orion/world-shared/cph161/jyc/andes/sw/anaconda3/2022.10/envs/hydragnn/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py
```

**Comment by jychoi-hpc** [comment]
I think it runs now. You can merge if it looks ok.

**Pull request merged**
